In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import PolynomialFeatures
import warnings
warnings.filterwarnings("ignore")
np.random.seed(42)
from sklearn.tree.export import export_text

# Logistic Regression Model

In [2]:
df = pd.read_csv("E:\ML\DataSets\loan_data.csv")

In [3]:
df.head()

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   
4              1         credit_card    0.1426       102.92       11.299732   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   
1  14.29   707        2760.000000      33623        76.7               0   
2  11.63   682        4710.000000       3511        25.6               1   
3   8.10   712        2699.958333      33667        73.2               1   
4  14.97   667        4066.000000       4740        39.5               0   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0  
1            0        0               0  
2            0        0               0  
3            0        0               0  
4            1        0               0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   credit.policy      9578 non-null   int64  
 1   purpose            9578 non-null   object 
 2   int.rate           9578 non-null   float64
 3   installment        9578 non-null   float64
 4   log.annual.inc     9578 non-null   float64
 5   dti                9578 non-null   float64
 6   fico               9578 non-null   int64  
 7   days.with.cr.line  9578 non-null   float64
 8   revol.bal          9578 non-null   int64  
 9   revol.util         9578 non-null   float64
 10  inq.last.6mths     9578 non-null   int64  
 11  delinq.2yrs        9578 non-null   int64  
 12  pub.rec            9578 non-null   int64  
 13  not.fully.paid     9578 non-null   int64  
dtypes: float64(6), int64(7), object(1)
memory usage: 1.0+ MB


In [5]:
df.dtypes

credit.policy          int64
purpose               object
int.rate             float64
installment          float64
log.annual.inc       float64
dti                  float64
fico                   int64
days.with.cr.line    float64
revol.bal              int64
revol.util           float64
inq.last.6mths         int64
delinq.2yrs            int64
pub.rec                int64
not.fully.paid         int64
dtype: object

In [12]:
df['credit.policy'].value_counts()

1    7710
0    1868
Name: credit.policy, dtype: int64

In [15]:
df['credit.policy']=df['credit.policy'].astype('category')

In [16]:
df.dtypes

credit.policy        category
purpose                object
int.rate              float64
installment           float64
log.annual.inc        float64
dti                   float64
fico                    int64
days.with.cr.line     float64
revol.bal               int64
revol.util            float64
inq.last.6mths          int64
delinq.2yrs             int64
pub.rec                 int64
not.fully.paid          int64
dtype: object

In [105]:
EncodedDF = pd.get_dummies(df[["purpose"]])

In [106]:
X = pd.concat([EncodedDF,df.drop(["purpose","not.fully.paid"],axis=1)],axis=1)

In [107]:
X.columns

Index(['purpose_all_other', 'purpose_credit_card',
       'purpose_debt_consolidation', 'purpose_educational',
       'purpose_home_improvement', 'purpose_major_purchase',
       'purpose_small_business', 'credit.policy', 'int.rate', 'installment',
       'log.annual.inc', 'dti', 'fico', 'days.with.cr.line', 'revol.bal',
       'revol.util', 'inq.last.6mths', 'delinq.2yrs', 'pub.rec'],
      dtype='object')

In [108]:
y = df[["not.fully.paid"]]

In [109]:
y.columns

Index(['not.fully.paid'], dtype='object')

In [110]:
from sklearn.model_selection import train_test_split

In [111]:
X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.2, random_state=101)

In [112]:
from sklearn.linear_model import LogisticRegression

In [113]:
log = LogisticRegression()

In [114]:
log.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [115]:
log.intercept_

array([0.00175079])

In [116]:
log.coef_

array([[ 6.35143018e-03, -7.72503808e-03, -8.90759919e-03,
         1.98243128e-03,  2.62041315e-03, -2.24996509e-03,
         9.67907515e-03, -1.98007821e-02,  1.14198377e-03,
         7.53760002e-04,  3.16253967e-03,  5.37475015e-03,
        -3.50325300e-03, -2.73791879e-05,  1.68177955e-06,
         7.43562402e-03,  1.24149879e-01,  3.11872684e-03,
         4.22149971e-03]])

In [117]:
predict = log.predict(X_test)

In [118]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix,roc_auc_score

In [119]:
print(accuracy_score(y_test,predict))

0.8460334029227558


In [120]:
print(confusion_matrix(y_test,predict))

[[1617    6]
 [ 289    4]]


In [121]:
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92      1623
           1       0.40      0.01      0.03       293

    accuracy                           0.85      1916
   macro avg       0.62      0.50      0.47      1916
weighted avg       0.78      0.85      0.78      1916



In [122]:
print(roc_auc_score(y_test,predict))

0.504977509731063


# Decision Tree Model

In [148]:
dt = DecisionTreeClassifier(max_depth=4)
dt.fit(X_train,y_train)
y_pred=dt.predict(X_test)
print(accuracy_score(y_test,y_pred))


0.8444676409185804


# Random Forest Model

In [124]:
from sklearn.ensemble import RandomForestClassifier


In [125]:
rf=RandomForestClassifier()

In [126]:
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [127]:
pred_rf=rf.predict(X_test)

In [129]:
print(accuracy_score(y_test,pred_rf))


0.8455114822546973
